### ISSUE TITLE
hello world using python and nodejs

### ISSUE THREAD

**Issue by razeghi** [SyntheticSemantics/ems#14]
Hello
Could you help me do the same thing as in the gift inside readme, aka communicate between modems and python?
I'm lost in the documents and I could not find what should I do.
Thanks

**Comment by razeghi** [comment]
Hello again
Excuse me because of typos
Could you help me do the same thing as in the gif inside readme, aka communicate between nodejs and python?
I'm lost in the documents and I could not find what should I do.
Thanks

**Comment by mogill** [comment]
Hi,

I created an example of Javascript/Python sharing objects which should give you a better starting point than the animated GIF.  

Please check out the `Examples/interlanguage.{py,js}` in the new release [v1.4.4](https://github.com/SyntheticSemantics/ems/tree/v1.4.4) and let me know if that helps.

            -J

**Comment by mogill** [comment]
I've just made additional improvements throughout the documentation and examples in v1.4.8.  If you have any other questions or problems, please feel free to (re-)open an issue.
