### ISSUE TITLE
EMS crash with JSON objects saved

### ISSUE THREAD

**Issue by inpras** [SyntheticSemantics/ems#15]
Hello,

ems is initialised in multiprocess environment

if (cluster.isMaster) {
  var start = Date.now();
  var persistent_data_options = {
      dimensions: [100000],
      heapSize: [10000000],
      useExisting: false,
      useMap: true,
      setFEtags: 'full',
      filename: '/tmp/persistent_shared_web_data.ems'
  };
....
}

in other process the useExisting flag is true

I add JSON objects (28 in number with fairly small structure of object) all is well till now.

With 29th object in array I get following error 

SyntaxError: Unexpected token `
    at Object.parse (native)
    at EMSreturnData (/home/telemon/node_modules/ems/nodejs/ems.js:211:25)
    at Object.EMSread [as read] (/home/telemon/node_modules/ems/nodejs/ems.js:308:12)

when I try to read it returns a partial object string

{"name":"FSM1","mbAddress":0,"mbSize":17,"` - notice the last quote 

with

SyntaxError: Unexpected token `

please let me know how do I resolve this?

**Comment by mogill** [comment]
I tried several variants of putting a back-quote in an attribute name but I'm not able to replicate this problem -- could you please paste here the original JSON that was stored which appears corrupt when it's read back?  Thanks,

            -J

**Comment by inpras** [comment]
This has to do with lesser heap size allocation, I am closing this as it was a trivial matter.
