### ISSUE TITLE
unexpected JSON format!

### ISSUE THREAD

**Issue by inpras** [SyntheticSemantics/ems#16]
Hello,

We are using ems in a multiple process environment using nodjs, this is a small embedded computer which fetches data from multiple ports converts them and sends to another port.

We are randomly getting an error which is a JSON parse error on a saved memory object when we read it using the key. The object is accessed at many places and we are doing just read and write operations on these objects.

Here is the screen shot of the error.

Is this something to do with we are running out of memory? If so how come other operations continue? 

By the way what we have in the shared memory is the set of JSON objects (read from a configuration file, some of them have an attribute called value(which is simple type mostly) are of type array of 200 odd integers.

we initialise ems like this (common file sharedMem.js)

`var ems = require('ems')(1, false, 'user');

var persistent_data;

var persistent_data_options = {
    dimensions: [50000],
    heapSize: [50000000],
    useExisting: true,
    useMap: true,
    setFEtags: 'full',
    filename: '/tmp/persistent_shared_web_data.ems'
};

module.exports = {
    sharedMem : ems.new(persistent_data_options)
}
`
we use sharedMem in clients 

`
var persistent_data = require('./sharedMem').sharedMem;
//somewhere down the line
prm = persistent_data.read(currPrm.name); //or write
`
main module (master since we are using cluster) initialisation is done as follows

`var persistent_data_options = {
      dimensions: [50000],
      heapSize: [50000000],
      useExisting: false,
      useMap: true,
      setFEtags: 'full',
      filename: '/tmp/persistent_shared_web_data.ems'
  };`

 Here is the error
![error](https://user-images.githubusercontent.com/17897854/29668547-428768b2-88fe-11e7-829f-2227d9d818ae.JPG)

Any help in this regard will be greatly appreciated.

Regards,
Prasanna

**Comment by mogill** [comment]
Hi Prasanna,

When updating shared objects in a parallel context (i.e.: two or more processes could potentially access the object simultaneously) be sure to use the thread-safe `readFE` and `writeEF` instead of the unprotected `read` and `write`.  This idiom is fairly common with EMS, it serializes access to this specific `key`:

```javascript
let tmp = shared.readFE(key);  // Read key when full and atomically mark empty
// Other processes also trying to use key are blocked because key is now empty
// Safely do work involving tmp, possibly modifying it
shared.writeEF(key, tmp);  // Write tmp back to key and atomically mark it full
// Another process that was blocked waiting for key can now safely proceed
```

Without the multithreaded protection two writers may simultaneously write to the same memory causing corruption which can look like a random combination of the two write operations jumbled together.  `readFE` and `writeEF` guarantee objects get written atomically.

Let me know if that helps,

            -J

**Comment by mogill** [comment]
I haven't heard back so I'm going to close this issue, but if you're still having problems feel free to re-open this again later.
