### ISSUE TITLE
This doesn't seem to compile for me on NodeJS 0.12.1 on OSX

### ISSUE THREAD

**Issue by eabovsky** [SyntheticSemantics/ems#4]
CXX(target) Release/obj.target/ems/ems.o
../ems.cpp:250:5: error: use of undeclared identifier 'nanosleep'
    NANOSLEEP;
    ^
../ems.cpp:155:5: note: expanded from macro 'NANOSLEEP'
    nanosleep(&sleep_time, NULL);               \
    ^
../ems.cpp:265:5: error: use of undeclared identifier 'nanosleep'
    NANOSLEEP;
    ^
../ems.cpp:155:5: note: expanded from macro 'NANOSLEEP'
    nanosleep(&sleep_time, NULL);               \
    ^
../ems.cpp:352:7: error: use of undeclared identifier 'nanosleep'
      NANOSLEEP;
      ^
../ems.cpp:155:5: note: expanded from macro 'NANOSLEEP'
    nanosleep(&sleep_time, NULL);               \
    ^
../ems.cpp:392:32: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
uint64_t EMSreadIndexMap(const v8::Arguments& args)
                               ^~~~~~~~~~~~~
                               v8::internal::Arguments
/var/folders/mr/cr6pnwvs5578w22byhjcxkgc0000gn/T/.node-gyp/0.12.1/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../ems.cpp:394:19: error: calling a protected constructor of class 'v8::HandleScope'
  v8::HandleScope scope;
                  ^
/var/folders/mr/cr6pnwvs5578w22byhjcxkgc0000gn/T/.node-gyp/0.12.1/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../ems.cpp:395:3: error: unexpected namespace name 'Buffer': expected expression
  EMS_DECL(args);
  ^
../ems.cpp:325:9: note: expanded from macro 'EMS_DECL'
  node::Buffer *buffer = node::ObjectWrap::Unwrap<node::Buffer>(args.This()->GetHiddenValue(buffer_symbol)->ToObject()); \
        ^
../ems.cpp:395:3: error: use of undeclared identifier 'buffer'
../ems.cpp:325:17: note: expanded from macro 'EMS_DECL'
  node::Buffer *buffer = node::ObjectWrap::Unwrap<node::Buffer>(args.This()->GetHiddenValue(buffer_symbol)->ToObject()); \
                ^
../ems.cpp:395:3: error: no member named 'ObjectWrap' in namespace 'node'
  EMS_DECL(args);
  ^~~~~~~~~~~~~~
../ems.cpp:325:32: note: expanded from macro 'EMS_DECL'
  node::Buffer *buffer = node::ObjectWrap::Unwrap<node::Buffer>(args.This()->GetHiddenValue(buffer_symbol)->ToObject()); \
                         ~~~~~~^
../ems.cpp:395:3: error: unexpected namespace name 'Buffer': expected expression
../ems.cpp:325:57: note: expanded from macro 'EMS_DECL'
  node::Buffer *buffer = node::ObjectWrap::Unwrap<node::Buffer>(args.This()->GetHiddenValue(buffer_symbol)->ToObject()); \
                                                        ^
../ems.cpp:395:3: error: member access into incomplete type 'const v8::internal::Arguments'
../ems.cpp:325:69: note: expanded from macro 'EMS_DECL'
  node::Buffer *buffer = node::ObjectWrap::Unwrap<node::Buffer>(args.This()->GetHiddenValue(buffer_symbol)->ToObject()); \
                                                                    ^
/var/folders/mr/cr6pnwvs5578w22byhjcxkgc0000gn/T/.node-gyp/0.12.1/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../ems.cpp:395:3: error: use of undeclared identifier 'buffer'
  EMS_DECL(args);
  ^
../ems.cpp:326:40: note: expanded from macro 'EMS_DECL'
  char*    emsBuf = static_cast<char*>(buffer->handle_->GetIndexedPropertiesExternalArrayData())
                                       ^
../ems.cpp:402:46: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int       idxType     = EMSv8toEMStype(args[0], false);
                                         ~~~~^~
../ems.cpp:224:4: note: expanded from macro 'EMSv8toEMStype'
   arg->IsInt32()                     ? EMS_INTEGER :                   \
   ^
../ems.cpp:402:46: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int       idxType     = EMSv8toEMStype(args[0], false);
                                         ~~~~^~
../ems.cpp:225:4: note: expanded from macro 'EMSv8toEMStype'
   arg->IsNumber()                    ? EMS_FLOAT   :                   \
   ^
../ems.cpp:402:46: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int       idxType     = EMSv8toEMStype(args[0], false);
                                         ~~~~^~
../ems.cpp:226:5: note: expanded from macro 'EMSv8toEMStype'
   (arg->IsString() && !stringIsJSON) ? EMS_STRING  :                   \
    ^
../ems.cpp:402:46: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int       idxType     = EMSv8toEMStype(args[0], false);
                                         ~~~~^~
../ems.cpp:227:5: note: expanded from macro 'EMSv8toEMStype'
   (arg->IsString() &&  stringIsJSON) ? EMS_JSON  :                     \
    ^
../ems.cpp:402:46: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int       idxType     = EMSv8toEMStype(args[0], false);
                                         ~~~~^~
../ems.cpp:228:4: note: expanded from macro 'EMSv8toEMStype'
   arg->IsBoolean()                   ? EMS_BOOLEAN :                   \
   ^
../ems.cpp:402:46: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int       idxType     = EMSv8toEMStype(args[0], false);
                                         ~~~~^~
../ems.cpp:229:4: note: expanded from macro 'EMSv8toEMStype'
   arg->IsUndefined()                 ? EMS_UNDEFINED:                  \
   ^
../ems.cpp:402:46: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int       idxType     = EMSv8toEMStype(args[0], false);
                                         ~~~~^~
../ems.cpp:230:4: note: expanded from macro 'EMSv8toEMStype'
   arg->IsUint32()                    ? EMS_INTEGER : -1                \
   ^
../ems.cpp:409:39: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  v8::String::Utf8Value argString(args[0]);
                                  ~~~~^~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/ems/ems.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/eugene/node-jpeg-turbo-scaler-master/node_modules/ems/ems
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

**Comment by mogill** [comment]
Regrettably, V8 has changed some APIs and I'm not able to keep EMS up to date.  Between ES6 proxies and shared memory parallel proposals (https://docs.google.com/document/d/1NDGA_gZJ7M7w1Bh8S0AoDyEqwDdRh4uSoTPSNn77PFk/edit) the best course of action for EMS is to re-implement it in pure Javascript.

Sorry I can't be of more help with support, but if you're still interested in shared memory parallelism for JS, I can recommend how you might get started using proxies and shared typed objects.

**Comment by evandrix** [comment]
Just checking in to say that I'm also experiencing the same (V8-related) compile failures on Node.js v4.2.3; OSX 10.10.5. Wanted to try it out, but looks like I've got to shelve this for now.

**Comment by novacrazy** [comment]
Would [NAN](https://github.com/nodejs/nan) help this project with V8 API inconsistencies across node versions? Seems like the go-to library for native addons.

**Comment by mogill** [comment]
Good news: It looks like I'll have time to convert the old V8 bindings before New Year's, so a fix is on the way.  NAN is definitely the right tool to use here, the problem has been finding time to do the work.  I plan to also fix some other bugs, design flaws, and add in some ES6isms as time allows.

**Comment by asilvas** [comment]
Great, looking forward to trying it out!

**Comment by mogill** [comment]
A major refactor has been checked in -- lots of bug fixes, new tests.  Tested on Mac & Linux, note that some Linux distros require user permissions to be set on /dev/shm, or to run jobs as root.

Please let me know if you have Q's or problems!

**Comment by mogill** [comment]
Didn't mean to close before you had a chance to try the new release.

**Comment by asilvas** [comment]
via `npm install` on latest for OSX.

```
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame

> ems@1.0.6 install /Users/asilvas/node_modules/ems
> node-gyp configure; node-gyp build

  CXX(target) Release/obj.target/ems/collectives.o
In file included from ../collectives.cc:32:
../ems.h:38:10: fatal error: 'node_modules/nan/nan.h' file not found
#include "node_modules/nan/nan.h"
         ^
1 error generated.
```

**Comment by mogill** [comment]
It looks like the dependencies (Nan, bindings, ffi) aren't automatically being installed as they are for me.  This may be a "new" npm feature, and the field in the package is being silently ignored.  I'm using npm 2.14.12 and node 4.2.4.

Please try first installing the dependencies manually, then ems:
npm install nan bindings ffi
npm install ems

**Comment by asilvas** [comment]
Same error, even if I do a global install of dependencies. Using npm `3.5.1`, node `4.2.2`.

**Comment by mogill** [comment]
I'm not able to replicate that on my Mac or AWS box.  You might try and edit ems.h to:
`#include "nan.h"`
without the path.  It must be some npm silliness I'll need to figure out how to replicate.  Just to be sure, are your npm, node, and node-gyp all installed in the "standard" place?

```sh
Mithril> npm install ems

> ref@1.3.1 install /private/tmp/DELETEME/node_modules/ems/node_modules/ffi/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node

> ffi@2.0.0 install /private/tmp/DELETEME/node_modules/ems/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/ffi_bindings.node
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame

> ems@1.0.6 install /private/tmp/DELETEME/node_modules/ems
> node-gyp configure; node-gyp build

  CXX(target) Release/obj.target/ems/collectives.o
  CXX(target) Release/obj.target/ems/ems.o
  CXX(target) Release/obj.target/ems/ems_alloc.o
  CXX(target) Release/obj.target/ems/loops.o
  CXX(target) Release/obj.target/ems/primitives.o
  CXX(target) Release/obj.target/ems/rmw.o
  SOLINK_MODULE(target) Release/ems.node
ems@1.0.6 node_modules/ems
├── bindings@1.2.1
├── nan@2.1.0
├── node-gyp@3.2.1 (graceful-fs@4.1.2, semver@5.1.0, fstream@1.0.8, mkdirp@0.5.1, tar@2.2.1, which@1.2.1, osenv@0.1.3, path-array@1.0.0, nopt@3.0.6, minimatch@1.0.0, npmlog@1.2.1, glob@4.5.3, rimraf@2.5.0, request@2.67.0)
└── ffi@2.0.0 (ref-struct@1.0.2, debug@2.2.0, ref@1.3.1)
Mithril> npm -v
2.14.12
Mithril> node -v
v4.2.4
Mithril> node-gyp -v
v3.2.1
Mithril> which node
/usr/local/bin/node
Mithril> which npm
/usr/local/bin/npm
Mithril> which node-gyp
/usr/local/bin/node-gyp
```

**Comment by asilvas** [comment]
We use `nvm`, so no, not the default location.

```
LMDV-ASILVAS:~ asilvas$ npm -v
3.5.1
LMDV-ASILVAS:~ asilvas$ node -v
v4.2.2
LMDV-ASILVAS:~ asilvas$ node-gyp -v
v3.2.1
LMDV-ASILVAS:~ asilvas$ which node
/Users/asilvas/.nvm/versions/node/v4.2.2/bin/node
LMDV-ASILVAS:~ asilvas$ which npm
/Users/asilvas/.nvm/versions/node/v4.2.2/bin/npm
LMDV-ASILVAS:~ asilvas$ which node-gyp
/Users/asilvas/.nvm/versions/node/v4.2.2/bin/node-gyp
```

**Comment by mogill** [comment]
I just pushed another fix -- thanks for being patient while I work through this.  This configuration should work with your nvm setup, let me know if it's still not building.

**Comment by asilvas** [comment]
+1

**Comment by mogill** [comment]
Looks like this is wrapped up, so I'm closing.  I just pushed an important bug fix so be sure to pull!  Thanks again for helping out!
